using System.Collections.Generic;
using System;
using System.Net;
namespace Data
{
    public interface IMemory//напрямую в память обращаться нельзя - только из медленной части БД; разбить на интерфейсы
    {
        int GetPagesLength();
        int GetPos();
        void SetPos(int value);
        int GetRegistrationLineCount();
        void DecrementAllRemoteIpHashesAttemptsCountersAndRemoveUnnecessaryByTimer();
        bool IncrementWithValueRemoteIpHashesAttemptsCountersAndGrantAccessAndAddIfNotPresented(IPAddress ipAddress, byte value);
        int GetPersonalMessagesToPublishCount();
        void InitializeRemoteIpHashesAttemptsCounter();
        string GetLastPage();
        IEnumerable<Pair> GetLoginPasswordHashesDeltaKeys();
        int GetTopicsToStartCount();
        int GetMessagesToPublishCount();
        string GetTemp();
        void SetTemp(string value);
        int GetPreRegistrationLineCount();
        int GetCaptchaMessagesCount();
        int GetDialogsToStartCount();
        string GetCaptchaPageToReturn();
        int GetCaptchaMessagesRegistrationDataCount();
        bool SpecialSearch(char c);
        int GetThreadsCount();
        void SetPageToReturnRegistrationData(string value);
        string GetPageToReturnRegistrationData();
        bool LoginPasswordAccIdHashesContainsKey(Pair pair);
        void LoginPasswordAccIdHashesAdd(Pair pair, int accountId);
        void LoginPasswordHashesDeltaRemove(Pair pair, out byte result);
        void InitializeLoginPasswordAccIdHashes();
        void InitializeLoginPasswordHashes();
        bool CaptchaMessagesContains(uint captcha);
        void InitializeLoginPasswordHashesDelta();
        bool LoginPasswordHashesContainsKey(Pair pair);
        void LoginPasswordHashesAdd(Pair pair, Guid? guid);
        bool NicksHashesKeysContains(uint hash);
        void InitializeNicksHashes();
        void NicksHashesAdd(uint nickHash, byte temp);
        string GetEndPointPageLocked(int index);
        void SetEndPointPageLocked(int index, string value);
        void InitializeEndPointPagesLocked(int size);
        string GetMainContentLocked();
        void SetMainContentLocked(string value);
        string GetMainPageLocked();
        void SetMainPageLocked(string value);
        void AddToMainPageLocked(string value);
        void DialogsToStartEnqueue(DialogData value);
        void InitializeDialogsToStart();
        DialogData DialogsToStartDequeue();
        void InitializePersonalMessagesToPublish();
        void PersonalMessagesToPublishEnqueue(MessageData value);
        MessageData PersonalMessagesToPublishDequeue();
        string[] GetDialogPagesArrayLocked(int index);
        void SetDialogPagesArrayLocked(int index, string[] value);
        void SetCaptchaPageToReturn(string value);
        string GetDialogPagesPageLocked(int arrayIndex, int pageIndex);
        void SetDialogPagesPageLocked(int arrayIndex, int pageIndex, string value);
        void AddToDialogPagesPageLocked(int arrayIndex, int pageIndex, string value);
        void InitializeDialogPagesLocked(string[][] value);
        int GetDialogPagesLengthLocked();
        void SetDialogPagesLengthLocked(int value);
        void CopyDialogPagesArraysToIncreasedSizeArraysAndFillGapsLocked();
        void SetDialogPagesPageDepthLocked(int index, int value);
        int GetDialogPagesPageDepthLocked(int index);
        void InitializeDialogPagesPageDepthLocked(int[] value);
        string GetMessage(int ownerId, int companionId, int messageId);
        string[] GetMessages(int ownerId, int companionId);
        void AddToPersonalPagesDepth(int id, int accountId);
        int GetPersonalPagesDepth(int id, int accountId);
        void SetPersonalPagesPage
                    (int id, int accountId, int depth, string page);
        void SetPersonalPagesMessagesArray
                        (int id, int accountId, string[] value);
        void InitializePrivateMessages();
        bool PersonalPagesContainsKey(OwnerId ownerId, CompanionId companionId, bool flag);
        void PersonalPagesAdd(OwnerId ownerId, CompanionId companionId, string[] newMsg, bool flag);
        bool PersonalPagesDepthsContainsKey(OwnerId ownerId, CompanionId companionId, bool flag);
        void PersonalPagesDepthsAdd(OwnerId ownerId, CompanionId companionId, bool flag);
        bool PersonalPagesDepthsKeysContains(OwnerId ownerId);
        bool PersonalPagesKeysContains(OwnerId ownerId);
        int GetPersonalPagesPageDepth(int accountId, int companionId);
        void PersonalPagesAdd(OwnerId ownerId, Dictionary<CompanionId, PrivateMessages> temp1);
        void PersonalPagesDepthsAdd(OwnerId ownerId,
                                                    Dictionary<CompanionId, int> temp2);
        string[] GetSectionPagesArrayLocked(int index);
        void SetSectionPagesArrayLocked(int index, string[] value);
        string GetSectionPagesPageLocked(int arrayIndex, int pageIndex);
        void SetSectionPagesPageLocked(int arrayIndex, int pageIndex, string value);
        void AddToSectionPagesPageLocked(int arrayIndex, int pageIndex, string value);
        void InitializeSectionPagesLocked(string[][] value);
        int GetSectionPagesLengthLocked();
        void SetSectionPagesLengthLocked(int value);
        void SetSectionPagesPageDepthLocked(int index, int value);
        int GetSectionPagesPageDepthLocked(int index);
        void InitializeSectionPagesPageDepthLocked(int[] value);
        void InitializeTopicsToStart();
        void SetSectionPagesArray(int endpointId);
        void SetThreadsCount(int threadsCount);
        void SetPages(string[] temp);
        void SetLastPage(string value);
        string GetPage(int num);
        void SetPage(int index, string value);
        void TopicsToStartEnqueue(TopicData value);
        string[] GetPages();
        TopicData TopicsToStartDequeue();
        void SetThreadPagesPageLocked(int arrayIndex, int pageIndex, string value);
        string GetThreadPagesPageLocked(int arrayIndex, int pageIndex);
        string[] GetThreadPagesArrayLocked(int arrayIndex);
        void SetThreadPagesArrayLocked(int arrayIndex, string[] value);
        void AddToThreadPagesPageLocked(int arrayIndex, int pageIndex, string value);
        void InitializeThreadPagesLocked(string[][] value);
        string[][] GetThreadPagesLocked();
        int GetThreadPagesPageDepthLocked(int index);
        void AddToThreadPagesPageDepthLocked(int index, int value);
        void SetThreadPagesPageDepthLocked(int index, int value);
        void InitializeThreadPagesPageDepthLocked(int[] value);
        int[] GetThreadPagesPageDepthLocked();
        int GetThreadPagesLengthLocked();
        void SetThreadPagesLengthLocked(int value);
        void InitializeMessagesToPublish();
        void MessagesToPublishEnqueue(MessageData messageData);
        MessageData MessagesToPublishDequeue();
        int GetLoginPasswordAccIdHashes(Pair pair);
        void PreRegistrationLineAdd(int val, PreRegBag bag);
        void InitializePreRegistrationLine();
        void InitializeRegistrationLine();
        void CaptchaMessagesRegistrationDataEnqueue(uint toQueue);
        void CaptchaMessagesRegistrationDataDequeue();
        void InitializeCaptchaMessagesRegistrationData();
        bool CaptchaMessagesRegistrationDataContains(uint captcha);
        void RegistrationLineRemove(int i, out RegBag regBag);
        void PreRegistrationLineRemove(int key, out PreRegBag preRegBag);
        bool LoginPasswordHashesDeltaContainsKey(Pair pair);
        void LoginPasswordHashesDeltaAdd(Pair pair, byte val);
        void RegistrationLineAdd(int val, RegBag regBag);
        void CaptchaMessagesEnqueue(uint toQueue);
        void InitializeCaptchaMessages();
        void CaptchaMessagesDequeue();
        bool LoginPasswordHashesValuesContains(Guid guid);
        void SetLoginPasswordHashesPairToken(Pair pair, Guid? token);
        void LoginPasswordHashesThroughIterationCheck(ref Pair pair, Guid guid);
    }
}